name: "Build"

on:
  pull_request:
  push:
    branches: 
      - master
      - next

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build