name: E2E Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - next
jobs:
  unittest:
    name: E2E Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: |
          npm ci
          npm install
          npm run build
      - name: Run E2E Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run test:e2e